language: python
python:
  - '3.7'
before_install:
  - chmod +x manage.py
install: 
  - pip install -r requirements.txt
env:
  - SQLITE_URL=sqlite:///my-local-sqlite.db
  - SECRET_KEY='secret_key'
script:
  -  python manage.py test